name: Clash2V2ray
on:
  schedule:
    - cron: "0 1 * * *"  # 每天 01:00 执行一次
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Convert Clash config to V2ray and Update Gist
        env:
          GIST_PAT: ${{ secrets.GIST_PAT }}
          GIST_LINK: ${{ secrets.GIST_LINK }}
        run: python -u subscribe/clash2vray.py 

      - name: Timestamp
        run: date
