name: Collect and Convert to V2ray

on:
  schedule:
    - cron: "30 0 * * MON"  # 每周一午夜半小时触发
  workflow_dispatch:       # 手动触发

concurrency:
  group: ${{ github.repository }}-v2ray
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai
  GIST_PAT: ${{ secrets.GIST_PAT }}
  GIST_LINK: ${{ secrets.GIST_LINK }}
  CUSTOMIZE_LINK: ${{ secrets.CUSTOMIZE_LINK }}
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}

jobs:
  convert_to_v2ray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install Dependencies
        run: pip3 install -r requirements.txt

      - name: Check Variables
        run:          if [ -z "$GIST_PAT" ]; then
              echo "Error: environment 'GIST_PAT' cannot be empty"
              exit 1
          fi
          if [ -z "$GIST_LINK" ]; then
              echo "Error: environment 'GIST_LINK' cannot be empty"
              exit 1
          fi
          LINK_PARTS=$(echo "$GIST_LINK" awk -F'/' 'NF==2 && $1!="" && $2!=""')
          if [ -z "$LINK_PARTS" ]; then
              echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
              exit 1

      - name: Convert to V2ray Subscriptions
        run: python -u collectvray.py

      - name: Timestamp
        run: date
