name: Delete
on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GIST_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1
