name: AUTO GIST VPN CRON

on:
  schedule:
    - cron: '0 */1 * * *'  # 北京时间每周日凌晨执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests tqdm
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        python -u subscribe/collect.py -s
      
    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        cd aggregate/data
        GIST_CONTENT=$(<proxies.yaml)
        JSON_PAYLOAD=$(jq -n --arg content "$GIST_CONTENT" \
          '{ "files": { "proxies.yaml": { "content": $content } } }')
        curl -X PATCH \
             -H "Authorization: token $GH_TOKEN" \
             -d "$JSON_PAYLOAD" \
             "https://api.github.com/gists/${{ secrets.GIST_ID }}"
