name: Push Notifications

on:
  push:
    branches:
      - main

jobs:
  delete-workflow-run-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Run Push Notifications action
      uses: dext7r/delete-workflow-run-logs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        per_page: 100
        expire_time: 7d
        status: completed
        repo: ${{ github.repository.repo }}
        owner: ${{ github.repository.owner }}
