name: SYNC FORK

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 确保获取所有历史记录

    - name: Configure git
      run: |
        git config --global user.name 'Auto merge'
        git config --global user.email 'Auto merge'

    - name: Add Upstream Remote
      run: |
        # 检查upstream是否已经存在，如果不存在，则添加
        if ! git remote | grep -q upstream; then
          git remote add upstream https://github.com/wzdnzd/aggregator.git
          echo "Upstream remote added."
        else
          echo "Upstream remote already exists."
        fi

    - name: Fetch from Upstream
      run: |
        git fetch upstream

    - name: Checking for Changes
      id: check
      run: |
        git checkout main
        git fetch upstream main
        UPSTREAM_SHA=$(git rev-parse upstream/main)
        LOCAL_SHA=$(git rev-parse main)
        if [ "$UPSTREAM_SHA" = "$LOCAL_SHA" ]; then
          echo "No changes to sync."
          echo "::set-output name=changes::false"
        else
          echo "Changes detected."
          echo "::set-output name=changes::true"
        fi

    - name: Merge Changes
      if: steps.check.outputs.changes == 'true'
      run: |
        git merge upstream/main
        git push origin main
        else
          echo "没有可同步的更新，跳过合并操作。"
        fi
