name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
    workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 确保获取所有历史记录

    - name: Configure git
      run: |
        git config --global user.name 'Auto merge'
        git config --global user.email 'Auto merge'

    - name: Sync with Upstream
      run: |
        git remote add upstream https://github.com/wzdnzd/aggregator.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push
